// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.neerogi.DrugTreatment;
import org.neerogi.Treatment;
import org.neerogi.web.DrugTreatmentController;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DrugTreatmentController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String DrugTreatmentController.create(@Valid DrugTreatment drugTreatment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, drugTreatment);
            return "drugtreatments/create";
        }
        uiModel.asMap().clear();
        drugTreatment.persist();
        return "redirect:/drugtreatments/" + encodeUrlPathSegment(drugTreatment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String DrugTreatmentController.createForm(Model uiModel) {
        populateEditForm(uiModel, new DrugTreatment());
        return "drugtreatments/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String DrugTreatmentController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("drugtreatment", DrugTreatment.findDrugTreatment(id));
        uiModel.addAttribute("itemId", id);
        return "drugtreatments/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String DrugTreatmentController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("drugtreatments", DrugTreatment.findDrugTreatmentEntries(firstResult, sizeNo));
            float nrOfPages = (float) DrugTreatment.countDrugTreatments() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("drugtreatments", DrugTreatment.findAllDrugTreatments());
        }
        return "drugtreatments/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String DrugTreatmentController.update(@Valid DrugTreatment drugTreatment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, drugTreatment);
            return "drugtreatments/update";
        }
        uiModel.asMap().clear();
        drugTreatment.merge();
        return "redirect:/drugtreatments/" + encodeUrlPathSegment(drugTreatment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String DrugTreatmentController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, DrugTreatment.findDrugTreatment(id));
        return "drugtreatments/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String DrugTreatmentController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        DrugTreatment drugTreatment = DrugTreatment.findDrugTreatment(id);
        drugTreatment.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/drugtreatments";
    }
    
    void DrugTreatmentController.populateEditForm(Model uiModel, DrugTreatment drugTreatment) {
        uiModel.addAttribute("drugTreatment", drugTreatment);
        uiModel.addAttribute("treatments", Treatment.findAllTreatments());
    }
    
    String DrugTreatmentController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
