// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import org.neerogi.domain.DrugTreatment;

privileged aspect DrugTreatment_Roo_Jpa_Entity {
    
    declare @type: DrugTreatment: @Entity;
    
    declare @type: DrugTreatment: @Table(name = "drug_treatment");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer DrugTreatment.id;
    
    public Integer DrugTreatment.getId() {
        return this.id;
    }
    
    public void DrugTreatment.setId(Integer id) {
        this.id = id;
    }
    
}
