// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;
import org.neerogi.domain.DrugTreatment;
import org.neerogi.domain.Treatment;

privileged aspect DrugTreatment_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "treatment_id", referencedColumnName = "id", nullable = false)
    private Treatment DrugTreatment.treatmentId;
    
    @Column(name = "name", length = 1000)
    @NotNull
    private String DrugTreatment.name;
    
    @Column(name = "medical_name", length = 1000)
    private String DrugTreatment.medicalName;
    
    @Column(name = "dose", length = 1000)
    private String DrugTreatment.dose;
    
    @Column(name = "frequency", length = 1000)
    private String DrugTreatment.frequency;
    
    @Column(name = "duration", length = 1000)
    private String DrugTreatment.duration;
    
    public Treatment DrugTreatment.getTreatmentId() {
        return treatmentId;
    }
    
    public void DrugTreatment.setTreatmentId(Treatment treatmentId) {
        this.treatmentId = treatmentId;
    }
    
    public String DrugTreatment.getName() {
        return name;
    }
    
    public void DrugTreatment.setName(String name) {
        this.name = name;
    }
    
    public String DrugTreatment.getMedicalName() {
        return medicalName;
    }
    
    public void DrugTreatment.setMedicalName(String medicalName) {
        this.medicalName = medicalName;
    }
    
    public String DrugTreatment.getDose() {
        return dose;
    }
    
    public void DrugTreatment.setDose(String dose) {
        this.dose = dose;
    }
    
    public String DrugTreatment.getFrequency() {
        return frequency;
    }
    
    public void DrugTreatment.setFrequency(String frequency) {
        this.frequency = frequency;
    }
    
    public String DrugTreatment.getDuration() {
        return duration;
    }
    
    public void DrugTreatment.setDuration(String duration) {
        this.duration = duration;
    }
    
}
