// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.Condition;
import org.neerogi.ConditionDataOnDemand;
import org.neerogi.ConditionIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConditionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConditionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConditionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConditionIntegrationTest: @Transactional;
    
    @Autowired
    ConditionDataOnDemand ConditionIntegrationTest.dod;
    
    @Test
    public void ConditionIntegrationTest.testCountConditions() {
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", dod.getRandomCondition());
        long count = Condition.countConditions();
        Assert.assertTrue("Counter for 'Condition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConditionIntegrationTest.testFindCondition() {
        Condition obj = dod.getRandomCondition();
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Condition' failed to provide an identifier", id);
        obj = Condition.findCondition(id);
        Assert.assertNotNull("Find method for 'Condition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Condition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConditionIntegrationTest.testFindAllConditions() {
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", dod.getRandomCondition());
        long count = Condition.countConditions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Condition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Condition> result = Condition.findAllConditions();
        Assert.assertNotNull("Find all method for 'Condition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Condition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConditionIntegrationTest.testFindConditionEntries() {
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", dod.getRandomCondition());
        long count = Condition.countConditions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Condition> result = Condition.findConditionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Condition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Condition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConditionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", dod.getRandomCondition());
        Condition obj = dod.getNewTransientCondition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Condition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Condition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Condition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConditionIntegrationTest.testRemove() {
        Condition obj = dod.getRandomCondition();
        Assert.assertNotNull("Data on demand for 'Condition' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Condition' failed to provide an identifier", id);
        obj = Condition.findCondition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Condition' with identifier '" + id + "'", Condition.findCondition(id));
    }
    
}
