// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.Doctors;
import org.neerogi.DoctorsDataOnDemand;
import org.neerogi.DoctorsIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DoctorsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DoctorsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DoctorsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DoctorsIntegrationTest: @Transactional;
    
    @Autowired
    DoctorsDataOnDemand DoctorsIntegrationTest.dod;
    
    @Test
    public void DoctorsIntegrationTest.testCountDoctorses() {
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", dod.getRandomDoctors());
        long count = Doctors.countDoctorses();
        Assert.assertTrue("Counter for 'Doctors' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DoctorsIntegrationTest.testFindDoctors() {
        Doctors obj = dod.getRandomDoctors();
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Doctors' failed to provide an identifier", id);
        obj = Doctors.findDoctors(id);
        Assert.assertNotNull("Find method for 'Doctors' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Doctors' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DoctorsIntegrationTest.testFindAllDoctorses() {
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", dod.getRandomDoctors());
        long count = Doctors.countDoctorses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Doctors', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Doctors> result = Doctors.findAllDoctorses();
        Assert.assertNotNull("Find all method for 'Doctors' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Doctors' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DoctorsIntegrationTest.testFindDoctorsEntries() {
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", dod.getRandomDoctors());
        long count = Doctors.countDoctorses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Doctors> result = Doctors.findDoctorsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Doctors' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Doctors' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DoctorsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", dod.getRandomDoctors());
        Doctors obj = dod.getNewTransientDoctors(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Doctors' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Doctors' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Doctors' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DoctorsIntegrationTest.testRemove() {
        Doctors obj = dod.getRandomDoctors();
        Assert.assertNotNull("Data on demand for 'Doctors' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Doctors' failed to provide an identifier", id);
        obj = Doctors.findDoctors(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Doctors' with identifier '" + id + "'", Doctors.findDoctors(id));
    }
    
}
