// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.Doctors;
import org.neerogi.DoctorsDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect DoctorsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DoctorsDataOnDemand: @Component;
    
    private Random DoctorsDataOnDemand.rnd = new SecureRandom();
    
    private List<Doctors> DoctorsDataOnDemand.data;
    
    public Doctors DoctorsDataOnDemand.getNewTransientDoctors(int index) {
        Doctors obj = new Doctors();
        setDesignation(obj, index);
        setName(obj, index);
        setRegistrationNo(obj, index);
        return obj;
    }
    
    public void DoctorsDataOnDemand.setDesignation(Doctors obj, int index) {
        String designation = "designation_" + index;
        if (designation.length() > 1000) {
            designation = designation.substring(0, 1000);
        }
        obj.setDesignation(designation);
    }
    
    public void DoctorsDataOnDemand.setName(Doctors obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public void DoctorsDataOnDemand.setRegistrationNo(Doctors obj, int index) {
        String registrationNo = "registrationNo_" + index;
        if (registrationNo.length() > 1000) {
            registrationNo = registrationNo.substring(0, 1000);
        }
        obj.setRegistrationNo(registrationNo);
    }
    
    public Doctors DoctorsDataOnDemand.getSpecificDoctors(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Doctors obj = data.get(index);
        Integer id = obj.getId();
        return Doctors.findDoctors(id);
    }
    
    public Doctors DoctorsDataOnDemand.getRandomDoctors() {
        init();
        Doctors obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Doctors.findDoctors(id);
    }
    
    public boolean DoctorsDataOnDemand.modifyDoctors(Doctors obj) {
        return false;
    }
    
    public void DoctorsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Doctors.findDoctorsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Doctors' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Doctors>();
        for (int i = 0; i < 10; i++) {
            Doctors obj = getNewTransientDoctors(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
