// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi;

import org.neerogi.HospitalDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HospitalDataOnDemand_Roo_Configurable {
    
    declare @type: HospitalDataOnDemand: @Configurable;
    
}
