// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.Condition;
import org.neerogi.ConditionDataOnDemand;
import org.neerogi.Investigation;
import org.neerogi.InvestigationDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InvestigationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InvestigationDataOnDemand: @Component;
    
    private Random InvestigationDataOnDemand.rnd = new SecureRandom();
    
    private List<Investigation> InvestigationDataOnDemand.data;
    
    @Autowired
    ConditionDataOnDemand InvestigationDataOnDemand.conditionDataOnDemand;
    
    public Investigation InvestigationDataOnDemand.getNewTransientInvestigation(int index) {
        Investigation obj = new Investigation();
        setConditionId(obj, index);
        setDate(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void InvestigationDataOnDemand.setConditionId(Investigation obj, int index) {
        Condition conditionId = conditionDataOnDemand.getRandomCondition();
        obj.setConditionId(conditionId);
    }
    
    public void InvestigationDataOnDemand.setDate(Investigation obj, int index) {
        Calendar date = Calendar.getInstance();
        obj.setDate(date);
    }
    
    public void InvestigationDataOnDemand.setDescription(Investigation obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1000) {
            description = description.substring(0, 1000);
        }
        obj.setDescription(description);
    }
    
    public void InvestigationDataOnDemand.setName(Investigation obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public Investigation InvestigationDataOnDemand.getSpecificInvestigation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Investigation obj = data.get(index);
        Integer id = obj.getId();
        return Investigation.findInvestigation(id);
    }
    
    public Investigation InvestigationDataOnDemand.getRandomInvestigation() {
        init();
        Investigation obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Investigation.findInvestigation(id);
    }
    
    public boolean InvestigationDataOnDemand.modifyInvestigation(Investigation obj) {
        return false;
    }
    
    public void InvestigationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Investigation.findInvestigationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Investigation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Investigation>();
        for (int i = 0; i < 10; i++) {
            Investigation obj = getNewTransientInvestigation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
