// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.AllergyType;
import org.neerogi.domain.AllergyTypeDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect AllergyTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AllergyTypeDataOnDemand: @Component;
    
    private Random AllergyTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<AllergyType> AllergyTypeDataOnDemand.data;
    
    public AllergyType AllergyTypeDataOnDemand.getNewTransientAllergyType(int index) {
        AllergyType obj = new AllergyType();
        setName(obj, index);
        return obj;
    }
    
    public void AllergyTypeDataOnDemand.setName(AllergyType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public AllergyType AllergyTypeDataOnDemand.getSpecificAllergyType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AllergyType obj = data.get(index);
        Integer id = obj.getId();
        return AllergyType.findAllergyType(id);
    }
    
    public AllergyType AllergyTypeDataOnDemand.getRandomAllergyType() {
        init();
        AllergyType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return AllergyType.findAllergyType(id);
    }
    
    public boolean AllergyTypeDataOnDemand.modifyAllergyType(AllergyType obj) {
        return false;
    }
    
    public void AllergyTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AllergyType.findAllergyTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AllergyType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AllergyType>();
        for (int i = 0; i < 10; i++) {
            AllergyType obj = getNewTransientAllergyType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
