// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.AllergyType;
import org.neerogi.domain.AllergyTypeDataOnDemand;
import org.neerogi.domain.AllergyTypeIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AllergyTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AllergyTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AllergyTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AllergyTypeIntegrationTest: @Transactional;
    
    @Autowired
    AllergyTypeDataOnDemand AllergyTypeIntegrationTest.dod;
    
    @Test
    public void AllergyTypeIntegrationTest.testCountAllergyTypes() {
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", dod.getRandomAllergyType());
        long count = AllergyType.countAllergyTypes();
        Assert.assertTrue("Counter for 'AllergyType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AllergyTypeIntegrationTest.testFindAllergyType() {
        AllergyType obj = dod.getRandomAllergyType();
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to provide an identifier", id);
        obj = AllergyType.findAllergyType(id);
        Assert.assertNotNull("Find method for 'AllergyType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AllergyType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AllergyTypeIntegrationTest.testFindAllAllergyTypes() {
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", dod.getRandomAllergyType());
        long count = AllergyType.countAllergyTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'AllergyType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AllergyType> result = AllergyType.findAllAllergyTypes();
        Assert.assertNotNull("Find all method for 'AllergyType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AllergyType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AllergyTypeIntegrationTest.testFindAllergyTypeEntries() {
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", dod.getRandomAllergyType());
        long count = AllergyType.countAllergyTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AllergyType> result = AllergyType.findAllergyTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AllergyType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AllergyType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AllergyTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", dod.getRandomAllergyType());
        AllergyType obj = dod.getNewTransientAllergyType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AllergyType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AllergyType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AllergyTypeIntegrationTest.testRemove() {
        AllergyType obj = dod.getRandomAllergyType();
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AllergyType' failed to provide an identifier", id);
        obj = AllergyType.findAllergyType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AllergyType' with identifier '" + id + "'", AllergyType.findAllergyType(id));
    }
    
}
