// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.Allergy;
import org.neerogi.domain.AllergyDataOnDemand;
import org.neerogi.domain.AllergyIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AllergyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AllergyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AllergyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AllergyIntegrationTest: @Transactional;
    
    @Autowired
    AllergyDataOnDemand AllergyIntegrationTest.dod;
    
    @Test
    public void AllergyIntegrationTest.testCountAllergys() {
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", dod.getRandomAllergy());
        long count = Allergy.countAllergys();
        Assert.assertTrue("Counter for 'Allergy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AllergyIntegrationTest.testFindAllergy() {
        Allergy obj = dod.getRandomAllergy();
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Allergy' failed to provide an identifier", id);
        obj = Allergy.findAllergy(id);
        Assert.assertNotNull("Find method for 'Allergy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Allergy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AllergyIntegrationTest.testFindAllAllergys() {
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", dod.getRandomAllergy());
        long count = Allergy.countAllergys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Allergy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Allergy> result = Allergy.findAllAllergys();
        Assert.assertNotNull("Find all method for 'Allergy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Allergy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AllergyIntegrationTest.testFindAllergyEntries() {
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", dod.getRandomAllergy());
        long count = Allergy.countAllergys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Allergy> result = Allergy.findAllergyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Allergy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Allergy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AllergyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", dod.getRandomAllergy());
        Allergy obj = dod.getNewTransientAllergy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Allergy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Allergy' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Allergy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AllergyIntegrationTest.testRemove() {
        Allergy obj = dod.getRandomAllergy();
        Assert.assertNotNull("Data on demand for 'Allergy' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Allergy' failed to provide an identifier", id);
        obj = Allergy.findAllergy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Allergy' with identifier '" + id + "'", Allergy.findAllergy(id));
    }
    
}
