// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import org.neerogi.domain.ConditionSubTypesIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ConditionSubTypesIntegrationTest_Roo_Configurable {
    
    declare @type: ConditionSubTypesIntegrationTest: @Configurable;
    
}
