// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.Doctor;
import org.neerogi.domain.DoctorDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect DoctorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DoctorDataOnDemand: @Component;
    
    private Random DoctorDataOnDemand.rnd = new SecureRandom();
    
    private List<Doctor> DoctorDataOnDemand.data;
    
    public Doctor DoctorDataOnDemand.getNewTransientDoctor(int index) {
        Doctor obj = new Doctor();
        setDesignation(obj, index);
        setName(obj, index);
        setRegistrationNo(obj, index);
        return obj;
    }
    
    public void DoctorDataOnDemand.setDesignation(Doctor obj, int index) {
        String designation = "designation_" + index;
        if (designation.length() > 1000) {
            designation = designation.substring(0, 1000);
        }
        obj.setDesignation(designation);
    }
    
    public void DoctorDataOnDemand.setName(Doctor obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public void DoctorDataOnDemand.setRegistrationNo(Doctor obj, int index) {
        String registrationNo = "registrationNo_" + index;
        if (registrationNo.length() > 1000) {
            registrationNo = registrationNo.substring(0, 1000);
        }
        obj.setRegistrationNo(registrationNo);
    }
    
    public Doctor DoctorDataOnDemand.getSpecificDoctor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Doctor obj = data.get(index);
        Integer id = obj.getId();
        return Doctor.findDoctor(id);
    }
    
    public Doctor DoctorDataOnDemand.getRandomDoctor() {
        init();
        Doctor obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Doctor.findDoctor(id);
    }
    
    public boolean DoctorDataOnDemand.modifyDoctor(Doctor obj) {
        return false;
    }
    
    public void DoctorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Doctor.findDoctorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Doctor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Doctor>();
        for (int i = 0; i < 10; i++) {
            Doctor obj = getNewTransientDoctor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
