// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.DrugTreatment;
import org.neerogi.domain.DrugTreatmentDataOnDemand;
import org.neerogi.domain.DrugTreatmentIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DrugTreatmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DrugTreatmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DrugTreatmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DrugTreatmentIntegrationTest: @Transactional;
    
    @Autowired
    DrugTreatmentDataOnDemand DrugTreatmentIntegrationTest.dod;
    
    @Test
    public void DrugTreatmentIntegrationTest.testCountDrugTreatments() {
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", dod.getRandomDrugTreatment());
        long count = DrugTreatment.countDrugTreatments();
        Assert.assertTrue("Counter for 'DrugTreatment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DrugTreatmentIntegrationTest.testFindDrugTreatment() {
        DrugTreatment obj = dod.getRandomDrugTreatment();
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to provide an identifier", id);
        obj = DrugTreatment.findDrugTreatment(id);
        Assert.assertNotNull("Find method for 'DrugTreatment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DrugTreatment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DrugTreatmentIntegrationTest.testFindAllDrugTreatments() {
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", dod.getRandomDrugTreatment());
        long count = DrugTreatment.countDrugTreatments();
        Assert.assertTrue("Too expensive to perform a find all test for 'DrugTreatment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DrugTreatment> result = DrugTreatment.findAllDrugTreatments();
        Assert.assertNotNull("Find all method for 'DrugTreatment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DrugTreatment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DrugTreatmentIntegrationTest.testFindDrugTreatmentEntries() {
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", dod.getRandomDrugTreatment());
        long count = DrugTreatment.countDrugTreatments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DrugTreatment> result = DrugTreatment.findDrugTreatmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DrugTreatment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DrugTreatment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DrugTreatmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", dod.getRandomDrugTreatment());
        DrugTreatment obj = dod.getNewTransientDrugTreatment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DrugTreatment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DrugTreatment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DrugTreatmentIntegrationTest.testRemove() {
        DrugTreatment obj = dod.getRandomDrugTreatment();
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DrugTreatment' failed to provide an identifier", id);
        obj = DrugTreatment.findDrugTreatment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DrugTreatment' with identifier '" + id + "'", DrugTreatment.findDrugTreatment(id));
    }
    
}
