// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.FollowUp;
import org.neerogi.domain.FollowUpDataOnDemand;
import org.neerogi.domain.FollowUpIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FollowUpIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FollowUpIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FollowUpIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: FollowUpIntegrationTest: @Transactional;
    
    @Autowired
    FollowUpDataOnDemand FollowUpIntegrationTest.dod;
    
    @Test
    public void FollowUpIntegrationTest.testCountFollowUps() {
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", dod.getRandomFollowUp());
        long count = FollowUp.countFollowUps();
        Assert.assertTrue("Counter for 'FollowUp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FollowUpIntegrationTest.testFindFollowUp() {
        FollowUp obj = dod.getRandomFollowUp();
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to provide an identifier", id);
        obj = FollowUp.findFollowUp(id);
        Assert.assertNotNull("Find method for 'FollowUp' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FollowUp' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FollowUpIntegrationTest.testFindAllFollowUps() {
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", dod.getRandomFollowUp());
        long count = FollowUp.countFollowUps();
        Assert.assertTrue("Too expensive to perform a find all test for 'FollowUp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FollowUp> result = FollowUp.findAllFollowUps();
        Assert.assertNotNull("Find all method for 'FollowUp' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FollowUp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FollowUpIntegrationTest.testFindFollowUpEntries() {
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", dod.getRandomFollowUp());
        long count = FollowUp.countFollowUps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FollowUp> result = FollowUp.findFollowUpEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FollowUp' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FollowUp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FollowUpIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", dod.getRandomFollowUp());
        FollowUp obj = dod.getNewTransientFollowUp(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FollowUp' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FollowUp' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FollowUpIntegrationTest.testRemove() {
        FollowUp obj = dod.getRandomFollowUp();
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FollowUp' failed to provide an identifier", id);
        obj = FollowUp.findFollowUp(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FollowUp' with identifier '" + id + "'", FollowUp.findFollowUp(id));
    }
    
}
