// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.FollowUp;
import org.neerogi.domain.FollowUpDataOnDemand;
import org.neerogi.domain.MedicalCondition;
import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FollowUpDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FollowUpDataOnDemand: @Component;
    
    private Random FollowUpDataOnDemand.rnd = new SecureRandom();
    
    private List<FollowUp> FollowUpDataOnDemand.data;
    
    @Autowired
    MedicalConditionDataOnDemand FollowUpDataOnDemand.medicalConditionDataOnDemand;
    
    public FollowUp FollowUpDataOnDemand.getNewTransientFollowUp(int index) {
        FollowUp obj = new FollowUp();
        setConditionId(obj, index);
        setFollowUpConditionId(obj, index);
        return obj;
    }
    
    public void FollowUpDataOnDemand.setConditionId(FollowUp obj, int index) {
        MedicalCondition conditionId = medicalConditionDataOnDemand.getRandomMedicalCondition();
        obj.setConditionId(conditionId);
    }
    
    public void FollowUpDataOnDemand.setFollowUpConditionId(FollowUp obj, int index) {
        String followUpConditionId = "followUpConditionId_" + index;
        if (followUpConditionId.length() > 1000) {
            followUpConditionId = followUpConditionId.substring(0, 1000);
        }
        obj.setFollowUpConditionId(followUpConditionId);
    }
    
    public FollowUp FollowUpDataOnDemand.getSpecificFollowUp(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FollowUp obj = data.get(index);
        Integer id = obj.getId();
        return FollowUp.findFollowUp(id);
    }
    
    public FollowUp FollowUpDataOnDemand.getRandomFollowUp() {
        init();
        FollowUp obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return FollowUp.findFollowUp(id);
    }
    
    public boolean FollowUpDataOnDemand.modifyFollowUp(FollowUp obj) {
        return false;
    }
    
    public void FollowUpDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FollowUp.findFollowUpEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FollowUp' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FollowUp>();
        for (int i = 0; i < 10; i++) {
            FollowUp obj = getNewTransientFollowUp(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
