// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.Hospital;
import org.neerogi.domain.HospitalDataOnDemand;
import org.neerogi.domain.HospitalIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HospitalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HospitalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HospitalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: HospitalIntegrationTest: @Transactional;
    
    @Autowired
    HospitalDataOnDemand HospitalIntegrationTest.dod;
    
    @Test
    public void HospitalIntegrationTest.testCountHospitals() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = Hospital.countHospitals();
        Assert.assertTrue("Counter for 'Hospital' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HospitalIntegrationTest.testFindHospital() {
        Hospital obj = dod.getRandomHospital();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide an identifier", id);
        obj = Hospital.findHospital(id);
        Assert.assertNotNull("Find method for 'Hospital' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Hospital' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HospitalIntegrationTest.testFindAllHospitals() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = Hospital.countHospitals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Hospital', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Hospital> result = Hospital.findAllHospitals();
        Assert.assertNotNull("Find all method for 'Hospital' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Hospital' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HospitalIntegrationTest.testFindHospitalEntries() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        long count = Hospital.countHospitals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Hospital> result = Hospital.findHospitalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Hospital' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Hospital' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HospitalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", dod.getRandomHospital());
        Hospital obj = dod.getNewTransientHospital(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Hospital' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Hospital' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HospitalIntegrationTest.testRemove() {
        Hospital obj = dod.getRandomHospital();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hospital' failed to provide an identifier", id);
        obj = Hospital.findHospital(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Hospital' with identifier '" + id + "'", Hospital.findHospital(id));
    }
    
}
