// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.MedicalCondition;
import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.neerogi.domain.MedicalConditionIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MedicalConditionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MedicalConditionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MedicalConditionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MedicalConditionIntegrationTest: @Transactional;
    
    @Autowired
    MedicalConditionDataOnDemand MedicalConditionIntegrationTest.dod;
    
    @Test
    public void MedicalConditionIntegrationTest.testCountMedicalConditions() {
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", dod.getRandomMedicalCondition());
        long count = MedicalCondition.countMedicalConditions();
        Assert.assertTrue("Counter for 'MedicalCondition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MedicalConditionIntegrationTest.testFindMedicalCondition() {
        MedicalCondition obj = dod.getRandomMedicalCondition();
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to provide an identifier", id);
        obj = MedicalCondition.findMedicalCondition(id);
        Assert.assertNotNull("Find method for 'MedicalCondition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MedicalCondition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MedicalConditionIntegrationTest.testFindAllMedicalConditions() {
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", dod.getRandomMedicalCondition());
        long count = MedicalCondition.countMedicalConditions();
        Assert.assertTrue("Too expensive to perform a find all test for 'MedicalCondition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MedicalCondition> result = MedicalCondition.findAllMedicalConditions();
        Assert.assertNotNull("Find all method for 'MedicalCondition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MedicalCondition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MedicalConditionIntegrationTest.testFindMedicalConditionEntries() {
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", dod.getRandomMedicalCondition());
        long count = MedicalCondition.countMedicalConditions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MedicalCondition> result = MedicalCondition.findMedicalConditionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MedicalCondition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MedicalCondition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MedicalConditionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", dod.getRandomMedicalCondition());
        MedicalCondition obj = dod.getNewTransientMedicalCondition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MedicalCondition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MedicalCondition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MedicalConditionIntegrationTest.testRemove() {
        MedicalCondition obj = dod.getRandomMedicalCondition();
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalCondition' failed to provide an identifier", id);
        obj = MedicalCondition.findMedicalCondition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MedicalCondition' with identifier '" + id + "'", MedicalCondition.findMedicalCondition(id));
    }
    
}
