// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.MedicalConditionSubType;
import org.neerogi.domain.MedicalConditionSubTypeDataOnDemand;
import org.neerogi.domain.MedicalConditionSubTypeIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MedicalConditionSubTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MedicalConditionSubTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MedicalConditionSubTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MedicalConditionSubTypeIntegrationTest: @Transactional;
    
    @Autowired
    MedicalConditionSubTypeDataOnDemand MedicalConditionSubTypeIntegrationTest.dod;
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testCountMedicalConditionSubTypes() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", dod.getRandomMedicalConditionSubType());
        long count = MedicalConditionSubType.countMedicalConditionSubTypes();
        Assert.assertTrue("Counter for 'MedicalConditionSubType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testFindMedicalConditionSubType() {
        MedicalConditionSubType obj = dod.getRandomMedicalConditionSubType();
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to provide an identifier", id);
        obj = MedicalConditionSubType.findMedicalConditionSubType(id);
        Assert.assertNotNull("Find method for 'MedicalConditionSubType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MedicalConditionSubType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testFindAllMedicalConditionSubTypes() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", dod.getRandomMedicalConditionSubType());
        long count = MedicalConditionSubType.countMedicalConditionSubTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'MedicalConditionSubType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MedicalConditionSubType> result = MedicalConditionSubType.findAllMedicalConditionSubTypes();
        Assert.assertNotNull("Find all method for 'MedicalConditionSubType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MedicalConditionSubType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testFindMedicalConditionSubTypeEntries() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", dod.getRandomMedicalConditionSubType());
        long count = MedicalConditionSubType.countMedicalConditionSubTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MedicalConditionSubType> result = MedicalConditionSubType.findMedicalConditionSubTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MedicalConditionSubType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MedicalConditionSubType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", dod.getRandomMedicalConditionSubType());
        MedicalConditionSubType obj = dod.getNewTransientMedicalConditionSubType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MedicalConditionSubType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MedicalConditionSubType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MedicalConditionSubTypeIntegrationTest.testRemove() {
        MedicalConditionSubType obj = dod.getRandomMedicalConditionSubType();
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalConditionSubType' failed to provide an identifier", id);
        obj = MedicalConditionSubType.findMedicalConditionSubType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MedicalConditionSubType' with identifier '" + id + "'", MedicalConditionSubType.findMedicalConditionSubType(id));
    }
    
}
