// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.Consultation;
import org.neerogi.domain.ConsultationDataOnDemand;
import org.neerogi.domain.MedicalCondition;
import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.neerogi.domain.MedicalConditionSubType;
import org.neerogi.domain.MedicalConditionSubTypeDataOnDemand;
import org.neerogi.domain.MedicalConditionType;
import org.neerogi.domain.MedicalConditionTypeDataOnDemand;
import org.neerogi.domain.Patient;
import org.neerogi.domain.PatientDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MedicalConditionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedicalConditionDataOnDemand: @Component;
    
    private Random MedicalConditionDataOnDemand.rnd = new SecureRandom();
    
    private List<MedicalCondition> MedicalConditionDataOnDemand.data;
    
    @Autowired
    ConsultationDataOnDemand MedicalConditionDataOnDemand.consultationDataOnDemand;
    
    @Autowired
    MedicalConditionSubTypeDataOnDemand MedicalConditionDataOnDemand.medicalConditionSubTypeDataOnDemand;
    
    @Autowired
    MedicalConditionTypeDataOnDemand MedicalConditionDataOnDemand.medicalConditionTypeDataOnDemand;
    
    @Autowired
    PatientDataOnDemand MedicalConditionDataOnDemand.patientDataOnDemand;
    
    public MedicalCondition MedicalConditionDataOnDemand.getNewTransientMedicalCondition(int index) {
        MedicalCondition obj = new MedicalCondition();
        setConsultation(obj, index);
        setDescription(obj, index);
        setFirstSymptomDate(obj, index);
        setFollowUp(obj, index);
        setLastSymptomDate(obj, index);
        setMedicalConditionSubType(obj, index);
        setMedicalConditionType(obj, index);
        setName(obj, index);
        setPatient(obj, index);
        return obj;
    }
    
    public void MedicalConditionDataOnDemand.setConsultation(MedicalCondition obj, int index) {
        Consultation consultation = consultationDataOnDemand.getRandomConsultation();
        obj.setConsultation(consultation);
    }
    
    public void MedicalConditionDataOnDemand.setDescription(MedicalCondition obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void MedicalConditionDataOnDemand.setFirstSymptomDate(MedicalCondition obj, int index) {
        Calendar firstSymptomDate = Calendar.getInstance();
        obj.setFirstSymptomDate(firstSymptomDate);
    }
    
    public void MedicalConditionDataOnDemand.setFollowUp(MedicalCondition obj, int index) {
        Boolean followUp = true;
        obj.setFollowUp(followUp);
    }
    
    public void MedicalConditionDataOnDemand.setLastSymptomDate(MedicalCondition obj, int index) {
        Calendar lastSymptomDate = Calendar.getInstance();
        obj.setLastSymptomDate(lastSymptomDate);
    }
    
    public void MedicalConditionDataOnDemand.setMedicalConditionSubType(MedicalCondition obj, int index) {
        MedicalConditionSubType medicalConditionSubType = medicalConditionSubTypeDataOnDemand.getRandomMedicalConditionSubType();
        obj.setMedicalConditionSubType(medicalConditionSubType);
    }
    
    public void MedicalConditionDataOnDemand.setMedicalConditionType(MedicalCondition obj, int index) {
        MedicalConditionType medicalConditionType = medicalConditionTypeDataOnDemand.getRandomMedicalConditionType();
        obj.setMedicalConditionType(medicalConditionType);
    }
    
    public void MedicalConditionDataOnDemand.setName(MedicalCondition obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public void MedicalConditionDataOnDemand.setPatient(MedicalCondition obj, int index) {
        Patient patient = patientDataOnDemand.getRandomPatient();
        obj.setPatient(patient);
    }
    
    public MedicalCondition MedicalConditionDataOnDemand.getSpecificMedicalCondition(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MedicalCondition obj = data.get(index);
        Integer id = obj.getId();
        return MedicalCondition.findMedicalCondition(id);
    }
    
    public MedicalCondition MedicalConditionDataOnDemand.getRandomMedicalCondition() {
        init();
        MedicalCondition obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return MedicalCondition.findMedicalCondition(id);
    }
    
    public boolean MedicalConditionDataOnDemand.modifyMedicalCondition(MedicalCondition obj) {
        return false;
    }
    
    public void MedicalConditionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MedicalCondition.findMedicalConditionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MedicalCondition' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MedicalCondition>();
        for (int i = 0; i < 10; i++) {
            MedicalCondition obj = getNewTransientMedicalCondition(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
