// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.MedicalConditionType;
import org.neerogi.domain.MedicalConditionTypeDataOnDemand;
import org.neerogi.domain.MedicalConditionTypeIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MedicalConditionTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MedicalConditionTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MedicalConditionTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MedicalConditionTypeIntegrationTest: @Transactional;
    
    @Autowired
    MedicalConditionTypeDataOnDemand MedicalConditionTypeIntegrationTest.dod;
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testCountMedicalConditionTypes() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", dod.getRandomMedicalConditionType());
        long count = MedicalConditionType.countMedicalConditionTypes();
        Assert.assertTrue("Counter for 'MedicalConditionType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testFindMedicalConditionType() {
        MedicalConditionType obj = dod.getRandomMedicalConditionType();
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to provide an identifier", id);
        obj = MedicalConditionType.findMedicalConditionType(id);
        Assert.assertNotNull("Find method for 'MedicalConditionType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MedicalConditionType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testFindAllMedicalConditionTypes() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", dod.getRandomMedicalConditionType());
        long count = MedicalConditionType.countMedicalConditionTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'MedicalConditionType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MedicalConditionType> result = MedicalConditionType.findAllMedicalConditionTypes();
        Assert.assertNotNull("Find all method for 'MedicalConditionType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MedicalConditionType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testFindMedicalConditionTypeEntries() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", dod.getRandomMedicalConditionType());
        long count = MedicalConditionType.countMedicalConditionTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MedicalConditionType> result = MedicalConditionType.findMedicalConditionTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MedicalConditionType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MedicalConditionType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", dod.getRandomMedicalConditionType());
        MedicalConditionType obj = dod.getNewTransientMedicalConditionType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MedicalConditionType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MedicalConditionType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MedicalConditionTypeIntegrationTest.testRemove() {
        MedicalConditionType obj = dod.getRandomMedicalConditionType();
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MedicalConditionType' failed to provide an identifier", id);
        obj = MedicalConditionType.findMedicalConditionType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MedicalConditionType' with identifier '" + id + "'", MedicalConditionType.findMedicalConditionType(id));
    }
    
}
