// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.MedicalConditionSubType;
import org.neerogi.domain.MedicalConditionSubTypeDataOnDemand;
import org.neerogi.domain.MedicalConditionType;
import org.neerogi.domain.MedicalConditionTypeDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MedicalConditionSubTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedicalConditionSubTypeDataOnDemand: @Component;
    
    private Random MedicalConditionSubTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<MedicalConditionSubType> MedicalConditionSubTypeDataOnDemand.data;
    
    @Autowired
    MedicalConditionTypeDataOnDemand MedicalConditionSubTypeDataOnDemand.medicalConditionTypeDataOnDemand;
    
    public MedicalConditionSubType MedicalConditionSubTypeDataOnDemand.getNewTransientMedicalConditionSubType(int index) {
        MedicalConditionSubType obj = new MedicalConditionSubType();
        setMedicalConditionType(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void MedicalConditionSubTypeDataOnDemand.setMedicalConditionType(MedicalConditionSubType obj, int index) {
        MedicalConditionType medicalConditionType = medicalConditionTypeDataOnDemand.getRandomMedicalConditionType();
        obj.setMedicalConditionType(medicalConditionType);
    }
    
    public void MedicalConditionSubTypeDataOnDemand.setName(MedicalConditionSubType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public MedicalConditionSubType MedicalConditionSubTypeDataOnDemand.getSpecificMedicalConditionSubType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MedicalConditionSubType obj = data.get(index);
        Integer id = obj.getId();
        return MedicalConditionSubType.findMedicalConditionSubType(id);
    }
    
    public MedicalConditionSubType MedicalConditionSubTypeDataOnDemand.getRandomMedicalConditionSubType() {
        init();
        MedicalConditionSubType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return MedicalConditionSubType.findMedicalConditionSubType(id);
    }
    
    public boolean MedicalConditionSubTypeDataOnDemand.modifyMedicalConditionSubType(MedicalConditionSubType obj) {
        return false;
    }
    
    public void MedicalConditionSubTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MedicalConditionSubType.findMedicalConditionSubTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MedicalConditionSubType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MedicalConditionSubType>();
        for (int i = 0; i < 10; i++) {
            MedicalConditionSubType obj = getNewTransientMedicalConditionSubType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
