// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.MedicalConditionType;
import org.neerogi.domain.MedicalConditionTypeDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect MedicalConditionTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedicalConditionTypeDataOnDemand: @Component;
    
    private Random MedicalConditionTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<MedicalConditionType> MedicalConditionTypeDataOnDemand.data;
    
    public MedicalConditionType MedicalConditionTypeDataOnDemand.getNewTransientMedicalConditionType(int index) {
        MedicalConditionType obj = new MedicalConditionType();
        setName(obj, index);
        return obj;
    }
    
    public void MedicalConditionTypeDataOnDemand.setName(MedicalConditionType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public MedicalConditionType MedicalConditionTypeDataOnDemand.getSpecificMedicalConditionType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MedicalConditionType obj = data.get(index);
        Integer id = obj.getId();
        return MedicalConditionType.findMedicalConditionType(id);
    }
    
    public MedicalConditionType MedicalConditionTypeDataOnDemand.getRandomMedicalConditionType() {
        init();
        MedicalConditionType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return MedicalConditionType.findMedicalConditionType(id);
    }
    
    public boolean MedicalConditionTypeDataOnDemand.modifyMedicalConditionType(MedicalConditionType obj) {
        return false;
    }
    
    public void MedicalConditionTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MedicalConditionType.findMedicalConditionTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MedicalConditionType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MedicalConditionType>();
        for (int i = 0; i < 10; i++) {
            MedicalConditionType obj = getNewTransientMedicalConditionType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
