// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MedicalConditionDataOnDemand_Roo_Configurable {
    
    declare @type: MedicalConditionDataOnDemand: @Configurable;
    
}
