// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.ConditionSubTypesDataOnDemand;
import org.neerogi.domain.MedicalCondition;
import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.neerogi.domain.Patient;
import org.neerogi.domain.PatientDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MedicalConditionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedicalConditionDataOnDemand: @Component;
    
    private Random MedicalConditionDataOnDemand.rnd = new SecureRandom();
    
    private List<MedicalCondition> MedicalConditionDataOnDemand.data;
    
    @Autowired
    ConditionSubTypesDataOnDemand MedicalConditionDataOnDemand.conditionSubTypesDataOnDemand;
    
    @Autowired
    PatientDataOnDemand MedicalConditionDataOnDemand.patientDataOnDemand;
    
    public MedicalCondition MedicalConditionDataOnDemand.getNewTransientMedicalCondition(int index) {
        MedicalCondition obj = new MedicalCondition();
        setConditionType(obj, index);
        setConsultationId(obj, index);
        setDescription(obj, index);
        setFollowUp(obj, index);
        setInitialDate(obj, index);
        setName(obj, index);
        setPatientId(obj, index);
        return obj;
    }
    
    public void MedicalConditionDataOnDemand.setConditionType(MedicalCondition obj, int index) {
        String conditionType = "conditionType_" + index;
        if (conditionType.length() > 1000) {
            conditionType = conditionType.substring(0, 1000);
        }
        obj.setConditionType(conditionType);
    }
    
    public void MedicalConditionDataOnDemand.setConsultationId(MedicalCondition obj, int index) {
        Integer consultationId = new Integer(index);
        obj.setConsultationId(consultationId);
    }
    
    public void MedicalConditionDataOnDemand.setDescription(MedicalCondition obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1000) {
            description = description.substring(0, 1000);
        }
        obj.setDescription(description);
    }
    
    public void MedicalConditionDataOnDemand.setFollowUp(MedicalCondition obj, int index) {
        Boolean followUp = true;
        obj.setFollowUp(followUp);
    }
    
    public void MedicalConditionDataOnDemand.setInitialDate(MedicalCondition obj, int index) {
        Calendar initialDate = Calendar.getInstance();
        obj.setInitialDate(initialDate);
    }
    
    public void MedicalConditionDataOnDemand.setName(MedicalCondition obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public void MedicalConditionDataOnDemand.setPatientId(MedicalCondition obj, int index) {
        Patient patientId = patientDataOnDemand.getRandomPatient();
        obj.setPatientId(patientId);
    }
    
    public MedicalCondition MedicalConditionDataOnDemand.getSpecificMedicalCondition(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MedicalCondition obj = data.get(index);
        Integer id = obj.getId();
        return MedicalCondition.findMedicalCondition(id);
    }
    
    public MedicalCondition MedicalConditionDataOnDemand.getRandomMedicalCondition() {
        init();
        MedicalCondition obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return MedicalCondition.findMedicalCondition(id);
    }
    
    public boolean MedicalConditionDataOnDemand.modifyMedicalCondition(MedicalCondition obj) {
        return false;
    }
    
    public void MedicalConditionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = MedicalCondition.findMedicalConditionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MedicalCondition' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MedicalCondition>();
        for (int i = 0; i < 10; i++) {
            MedicalCondition obj = getNewTransientMedicalCondition(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
