// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.Patient;
import org.neerogi.domain.PatientDataOnDemand;
import org.neerogi.domain.PatientIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PatientIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PatientIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PatientIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PatientIntegrationTest: @Transactional;
    
    @Autowired
    PatientDataOnDemand PatientIntegrationTest.dod;
    
    @Test
    public void PatientIntegrationTest.testCountPatients() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = Patient.countPatients();
        Assert.assertTrue("Counter for 'Patient' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PatientIntegrationTest.testFindPatient() {
        Patient obj = dod.getRandomPatient();
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide an identifier", id);
        obj = Patient.findPatient(id);
        Assert.assertNotNull("Find method for 'Patient' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Patient' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PatientIntegrationTest.testFindAllPatients() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = Patient.countPatients();
        Assert.assertTrue("Too expensive to perform a find all test for 'Patient', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Patient> result = Patient.findAllPatients();
        Assert.assertNotNull("Find all method for 'Patient' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Patient' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PatientIntegrationTest.testFindPatientEntries() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        long count = Patient.countPatients();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Patient> result = Patient.findPatientEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Patient' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Patient' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PatientIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", dod.getRandomPatient());
        Patient obj = dod.getNewTransientPatient(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Patient' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Patient' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PatientIntegrationTest.testRemove() {
        Patient obj = dod.getRandomPatient();
        Assert.assertNotNull("Data on demand for 'Patient' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patient' failed to provide an identifier", id);
        obj = Patient.findPatient(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Patient' with identifier '" + id + "'", Patient.findPatient(id));
    }
    
}
