// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.Patient;
import org.neerogi.domain.PatientDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect PatientDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PatientDataOnDemand: @Component;
    
    private Random PatientDataOnDemand.rnd = new SecureRandom();
    
    private List<Patient> PatientDataOnDemand.data;
    
    public Patient PatientDataOnDemand.getNewTransientPatient(int index) {
        Patient obj = new Patient();
        setAddress(obj, index);
        setDateOfBirth(obj, index);
        setGender(obj, index);
        setName(obj, index);
        setOccupation(obj, index);
        return obj;
    }
    
    public void PatientDataOnDemand.setAddress(Patient obj, int index) {
        String address = "address_" + index;
        if (address.length() > 1000) {
            address = address.substring(0, 1000);
        }
        obj.setAddress(address);
    }
    
    public void PatientDataOnDemand.setDateOfBirth(Patient obj, int index) {
        Calendar dateOfBirth = Calendar.getInstance();
        obj.setDateOfBirth(dateOfBirth);
    }
    
    public void PatientDataOnDemand.setGender(Patient obj, int index) {
        String gender = "gender_" + index;
        if (gender.length() > 1000) {
            gender = gender.substring(0, 1000);
        }
        obj.setGender(gender);
    }
    
    public void PatientDataOnDemand.setName(Patient obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public void PatientDataOnDemand.setOccupation(Patient obj, int index) {
        String occupation = "occupation_" + index;
        if (occupation.length() > 1000) {
            occupation = occupation.substring(0, 1000);
        }
        obj.setOccupation(occupation);
    }
    
    public Patient PatientDataOnDemand.getSpecificPatient(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Patient obj = data.get(index);
        Integer id = obj.getId();
        return Patient.findPatient(id);
    }
    
    public Patient PatientDataOnDemand.getRandomPatient() {
        init();
        Patient obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Patient.findPatient(id);
    }
    
    public boolean PatientDataOnDemand.modifyPatient(Patient obj) {
        return false;
    }
    
    public void PatientDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Patient.findPatientEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Patient' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Patient>();
        for (int i = 0; i < 10; i++) {
            Patient obj = getNewTransientPatient(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
