// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.Patient;
import org.neerogi.domain.PatientDataOnDemand;
import org.neerogi.domain.SocialHistory;
import org.neerogi.domain.SocialHistoryDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SocialHistoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SocialHistoryDataOnDemand: @Component;
    
    private Random SocialHistoryDataOnDemand.rnd = new SecureRandom();
    
    private List<SocialHistory> SocialHistoryDataOnDemand.data;
    
    @Autowired
    PatientDataOnDemand SocialHistoryDataOnDemand.patientDataOnDemand;
    
    public SocialHistory SocialHistoryDataOnDemand.getNewTransientSocialHistory(int index) {
        SocialHistory obj = new SocialHistory();
        setDescription(obj, index);
        setPatientId(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void SocialHistoryDataOnDemand.setDescription(SocialHistory obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1000) {
            description = description.substring(0, 1000);
        }
        obj.setDescription(description);
    }
    
    public void SocialHistoryDataOnDemand.setPatientId(SocialHistory obj, int index) {
        Patient patientId = patientDataOnDemand.getRandomPatient();
        obj.setPatientId(patientId);
    }
    
    public void SocialHistoryDataOnDemand.setType(SocialHistory obj, int index) {
        String type = "type_" + index;
        if (type.length() > 1000) {
            type = type.substring(0, 1000);
        }
        obj.setType(type);
    }
    
    public SocialHistory SocialHistoryDataOnDemand.getSpecificSocialHistory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SocialHistory obj = data.get(index);
        Integer id = obj.getId();
        return SocialHistory.findSocialHistory(id);
    }
    
    public SocialHistory SocialHistoryDataOnDemand.getRandomSocialHistory() {
        init();
        SocialHistory obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return SocialHistory.findSocialHistory(id);
    }
    
    public boolean SocialHistoryDataOnDemand.modifySocialHistory(SocialHistory obj) {
        return false;
    }
    
    public void SocialHistoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SocialHistory.findSocialHistoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SocialHistory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SocialHistory>();
        for (int i = 0; i < 10; i++) {
            SocialHistory obj = getNewTransientSocialHistory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
