// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neerogi.domain.Treatment;
import org.neerogi.domain.TreatmentDataOnDemand;
import org.neerogi.domain.TreatmentIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TreatmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TreatmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TreatmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TreatmentIntegrationTest: @Transactional;
    
    @Autowired
    TreatmentDataOnDemand TreatmentIntegrationTest.dod;
    
    @Test
    public void TreatmentIntegrationTest.testCountTreatments() {
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", dod.getRandomTreatment());
        long count = Treatment.countTreatments();
        Assert.assertTrue("Counter for 'Treatment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TreatmentIntegrationTest.testFindTreatment() {
        Treatment obj = dod.getRandomTreatment();
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Treatment' failed to provide an identifier", id);
        obj = Treatment.findTreatment(id);
        Assert.assertNotNull("Find method for 'Treatment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Treatment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TreatmentIntegrationTest.testFindAllTreatments() {
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", dod.getRandomTreatment());
        long count = Treatment.countTreatments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Treatment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Treatment> result = Treatment.findAllTreatments();
        Assert.assertNotNull("Find all method for 'Treatment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Treatment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TreatmentIntegrationTest.testFindTreatmentEntries() {
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", dod.getRandomTreatment());
        long count = Treatment.countTreatments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Treatment> result = Treatment.findTreatmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Treatment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Treatment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TreatmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", dod.getRandomTreatment());
        Treatment obj = dod.getNewTransientTreatment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Treatment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Treatment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Treatment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TreatmentIntegrationTest.testRemove() {
        Treatment obj = dod.getRandomTreatment();
        Assert.assertNotNull("Data on demand for 'Treatment' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Treatment' failed to provide an identifier", id);
        obj = Treatment.findTreatment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Treatment' with identifier '" + id + "'", Treatment.findTreatment(id));
    }
    
}
