// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.neerogi.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.neerogi.domain.MedicalCondition;
import org.neerogi.domain.MedicalConditionDataOnDemand;
import org.neerogi.domain.Treatment;
import org.neerogi.domain.TreatmentDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TreatmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TreatmentDataOnDemand: @Component;
    
    private Random TreatmentDataOnDemand.rnd = new SecureRandom();
    
    private List<Treatment> TreatmentDataOnDemand.data;
    
    @Autowired
    MedicalConditionDataOnDemand TreatmentDataOnDemand.medicalConditionDataOnDemand;
    
    public Treatment TreatmentDataOnDemand.getNewTransientTreatment(int index) {
        Treatment obj = new Treatment();
        setConditionId(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void TreatmentDataOnDemand.setConditionId(Treatment obj, int index) {
        MedicalCondition conditionId = medicalConditionDataOnDemand.getRandomMedicalCondition();
        obj.setConditionId(conditionId);
    }
    
    public void TreatmentDataOnDemand.setDescription(Treatment obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1000) {
            description = description.substring(0, 1000);
        }
        obj.setDescription(description);
    }
    
    public void TreatmentDataOnDemand.setName(Treatment obj, int index) {
        String name = "name_" + index;
        if (name.length() > 1000) {
            name = name.substring(0, 1000);
        }
        obj.setName(name);
    }
    
    public Treatment TreatmentDataOnDemand.getSpecificTreatment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Treatment obj = data.get(index);
        Integer id = obj.getId();
        return Treatment.findTreatment(id);
    }
    
    public Treatment TreatmentDataOnDemand.getRandomTreatment() {
        init();
        Treatment obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Treatment.findTreatment(id);
    }
    
    public boolean TreatmentDataOnDemand.modifyTreatment(Treatment obj) {
        return false;
    }
    
    public void TreatmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Treatment.findTreatmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Treatment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Treatment>();
        for (int i = 0; i < 10; i++) {
            Treatment obj = getNewTransientTreatment(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
